channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Specify your Python version here
  - gymnasium>=0.28.1
  - numpy~=1.26.4
  - mujoco>=3.1.0
  - pytest~=8.1.1
  - quaternion~=2023.0.2
  - setuptools~=69.1.1
  - tqdm~=4.66.2
  - scipy~=1.12.0
  - pip:
    - ray=2.9.3
    - ray[rllib]~=2.9.3  # Use pip under dependencies if specific subpackages are needed
